title: LUGAN | Linux User Group ANcona
description: Governance and Code of LUGAN

google_analytics: G-LBLE8B6770

plugins:
- jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

defaults:
    - scope:
        path: "" # apply to all files
      values:
        layout: "default"
