title: LUGAN - Linux User Group ANcona
description: Governance and Code of LUGAN

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "" # apply to all files
    values:
      layout: "page" # use default page layout
